### ISSUE TITLE
8 hosts in list, only opens 7

### ISSUE THREAD

**Issue by edrozenberg** [olsonbg/dotfiles#5]
I gave it 8 hosts to open, opens 7 only. The last pane at the bottom (host 7) stretches all the way across instead of splitting to also show host 8.

**Comment by kevcampb** [comment]
Can you connect to the missing host directly without using ssh-multi?

**Comment by edrozenberg** [comment]
I just tested with many connections to the same host, for example:

```./ssh-multi.sh -d "host1 host1 host1 host1 host1 host1 host1 host1 host1"```

On my laptop it opens 5 panes. Makes sense that it cannot fit more panes vertically, but I would expect 6 panes, not 5. The bottom pane is always going full length across instead of being split like the upper panes.

**Comment by olsonbg** [comment]
Using @kevcampb  suggestion, #6 , I just added c654cb5651e3fb7132852bd9dc0363b1f84e5f80 , give it a try an let me know how it works.

**Comment by edrozenberg** [comment]
Fixed by the commit mentioned above, thanks!
