### ISSUE TITLE
Inability to open large numbers of panes

### ISSUE THREAD

**Issue by kevcampb** [olsonbg/dotfiles#6]
Getting the error message "create pane failed: pane too small" when starting with many hosts. Seems this is a new issue, possibly in a later release of tmux? The issue didn't occur before.

The following patch seems to work, although I have no idea of the details of how tmux layouts work.

```
--- ssh-multi.sh.1      2017-10-17 10:45:21.000000000 +0800
+++ ssh-multi.sh        2017-10-17 10:43:40.000000000 +0800
@@ -57,6 +57,7 @@
        for i in "${hosts[@]}"
        do
                        tmux split-window -t "${session}:${window}" -h "ssh $user$i"
+               tmux select-layout -t "${session}:${window}" tiled
        done

        tmux select-layout -t "${session}:${window}" tiled
```

Related to https://github.com/tmuxinator/tmuxinator/pull/48/files

**Comment by olsonbg** [comment]
Thanks @kevcampb . Try c654cb5651e3fb7132852bd9dc0363b1f84e5f80 and let me know how it works.
