### ISSUE TITLE
Suggestion - use unique tmux session names to allow multiple sessions

### ISSUE THREAD

**Issue by edrozenberg** [olsonbg/dotfiles#7]
Currently the ssh-multi script always uses the session name "sshmulti". This prevents being able to create multiple sets of tmux sessions in different terminal windows or tabs. When trying to create a second multi ssh tmux session, the second session attaches to the first (previous) session and all the panes get pulled into the same window.

Suggestion: use a unique session name within the script, such as "sshmulti-currenttimestamp" or "sshmulti-randomnumber"

**Comment by edrozenberg** [comment]
I'm currrently using this at the top:

```
session="sshmulti-`gdate +%s%N`"
```

Seems to work fine so far (but requires gdate from coreutils to generate nanosecond level timestamps). Otherwise for regular date with second-accuracy timestamps can use:

```
session="sshmulti-`date +%s`"
```

**Comment by olsonbg** [comment]
@edrozenberg , have you tried starting a tmux session first, then launching ssh-multi from there? You can launch ssh-multi from that first window as many times as you wish, and a new window will be created each time, connected to the hosts you specify. This way all your ssh-multi windows will be consolidated into one tmux session.

If this method does not suit your needs, I can look into having a unique session name.

P.S. I just uploaded a patch which fixed a warning when launching ssh-multi from inside a tmux session.

**Comment by olsonbg** [comment]
I just added another patch (d984810dffdc0630915fd5ed77eb5e8b65a80c5f), this one allows specifying the session name on the command line using the '-s' flag.

**Comment by edrozenberg** [comment]
Just tried the session option, works great! Thanks a lot.
